// import { IsString, IsArray, ValidateNested, IsNumber, IsObject } from 'class-validator';
// import { Type } from 'class-transformer';
// import { ApiProperty } from '@nestjs/swagger';

// class SyncPayloadDto {
//   @ApiProperty({ example: 'base64-iv', description: 'Initialization vector' })
//   @IsString()
//   iv: string;

//   @ApiProperty({ example: 'encrypted-base64', description: 'Encrypted content' })
//   @IsString()
//   content: string;

//   @ApiProperty({ example: 'base64-auth-tag', description: 'Authentication tag' })
//   @IsString()
//   tag: string;
// }

// export class SyncTransactionDto {
//   @ApiProperty({ example: 'txn-1234', description: 'Unique transaction ID for idempotency' })
//   @IsString()
//   transactionId: string;

//   @ApiProperty({ example: 1710672000000, description: 'Timestamp' })
//   @IsNumber()
//   timestamp: number;

//   @ApiProperty({ example: 'unique-nonce-abc', description: 'Cryptographic nonce' })
//   @IsString()
//   nonce: string;

//   @ApiProperty({ type: SyncPayloadDto, description: 'Encrypted payload details' })
//   @IsObject()
//   @ValidateNested()
//   @Type(() => SyncPayloadDto)
//   payload: SyncPayloadDto;

//   @ApiProperty({ example: 'base64-ed25519-signature', description: 'Signature of the request payload' })
//   @IsString()
//   signature: string;
// }

// export class SyncRequestDto {
//   @ApiProperty({ example: 'device-abc', description: 'Device ID initiating sync' })
//   @IsString()
//   deviceId: string;

//   @ApiProperty({ type: [SyncTransactionDto], description: 'List of transactions to sync' })
//   @IsArray()
//   @ValidateNested({ each: true })
//   @Type(() => SyncTransactionDto)
//   transactions: SyncTransactionDto[];
// }


import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsArray, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';
// import { SyncTransactionDto } from './sync-transaction.dto';
import {  IsNumber } from 'class-validator';

export class EncryptedPayloadDto {
  @ApiProperty({
    example: 'BASE64_ENCRYPTED_DATA',
    description: 'AES-256-GCM encrypted content (base64)',
  })
  @IsString()
  content: string;

  @ApiProperty({
    example: 'BASE64_IV',
    description: 'Initialization vector (base64)',
  })
  @IsString()
  iv: string;

  @ApiProperty({
    example: 'BASE64_AUTH_TAG',
    description: 'GCM authentication tag (base64)',
  })
  @IsString()
  tag: string;
}


export class SyncTransactionDto {
  @ApiProperty({
    example: 'txn-uuid-123',
    description: 'Unique transaction ID generated by client',
  })
  @IsString()
  transactionId: string;

  @ApiProperty({
    example: 1710000000000,
    description: 'Client timestamp in milliseconds',
  })
  @IsNumber()
  timestamp: number;

  @ApiProperty({
    example: 'random_nonce_123',
    description: 'Unique nonce per request to prevent replay attacks',
  })
  @IsString()
  nonce: string;

  @ApiProperty({
    type: EncryptedPayloadDto,
  })
  @ValidateNested()
  @Type(() => EncryptedPayloadDto)
  payload: EncryptedPayloadDto;

  @ApiProperty({
    example: 'BASE64_SIGNATURE',
    description: 'Ed25519 signature of the canonical JSON string payload',
  })
  @IsString()
  signature: string;
}

export class SyncRequestDto {
  @ApiProperty({
    example: 'device-123',
    description: 'Unique device identifier',
  })
  @IsString()
  deviceId: string;

  @ApiProperty({
    type: [SyncTransactionDto],
  })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => SyncTransactionDto)
  transactions: SyncTransactionDto[];
}


// import { EncryptedPayloadDto } from './encrypted-payload.dto';




