const crypto = require('crypto');

async function runFlow() {
  const BASE_URL = 'http://localhost:3000';
  const phone = '059' + Math.floor(1000000 + Math.random() * 9000000);
  const password = 'Password123!';
  const deviceId = 'device-' + crypto.randomUUID();

  console.log(`--- Starting Production Flow for user ${phone} ---`);

  try {
    // 1. Register User
    console.log('1. Registering user...');
    const registerRes = await fetch(`${BASE_URL}/auth/register`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ phone, password, name: 'Test User' }),
    });
    const userData = await registerRes.json();
    if (!registerRes.ok) throw new Error(`Register failed: ${JSON.stringify(userData)}`);
    console.log('✅ User registered:', userData.data.id);

    // 2. Login
    console.log('2. Logging in...');
    const loginRes = await fetch(`${BASE_URL}/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ phone, password }),
    });
    const authData = await loginRes.json();
    if (!loginRes.ok) throw new Error(`Login failed: ${JSON.stringify(authData)}`);
    const token = authData.data.access_token;
    console.log('✅ Login successful');

    // 3. Register Device (GET SERVER-GENERATED KEYS)
    console.log('3. Registering device (getting server-side keys)...');
    const deviceRes = await fetch(`${BASE_URL}/devices/register`, {
      method: 'POST',
      headers: { 
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}` 
      },
      body: JSON.stringify({
        deviceId: deviceId
      })
    });
    const deviceResult = await deviceRes.json();
    if (!deviceRes.ok) throw new Error(`Device register failed: ${JSON.stringify(deviceResult)}`);
    console.log('✅ Device registered and keys generated by server');

    const { privateKeyPem, aesKeyBase64 } = deviceResult;

    // 4. Simulate Client Encryption (Using the server's keys)
    console.log('4. Simulating client encryption with server keys...');
    const encryptRes = await fetch(`${BASE_URL}/crypto/simulate-encryption`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        deviceId: deviceId,
        // Pass the server's keys back to the simulator so it signs correctly
        privateKeyBase64: Buffer.from(privateKeyPem).toString('base64'),
        aesKeyBase64: aesKeyBase64,
        transactionData: {
          transactionId: crypto.randomUUID(),
          amount: 450.50,
          currency: 'USD',
          recipientId: 'user-999'
        }
      })
    });
    const encryptData = await encryptRes.json();
    if (!encryptRes.ok) throw new Error(`Encryption simulation failed: ${JSON.stringify(encryptData)}`);
    const syncPayload = encryptData.syncPayload;
    console.log('✅ Client payload prepared and signed');

    // 5. Sync Transactions
    console.log('5. Syncing transactions to server...');
    const syncRes = await fetch(`${BASE_URL}/sync`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(syncPayload)
    });
    const syncResult = await syncRes.json();
    if (!syncRes.ok) throw new Error(`Sync failed: ${JSON.stringify(syncResult)}`);
    console.log('✅ Sync successful! Final results:', JSON.stringify(syncResult, null, 2));

  } catch (error) {
    console.error('❌ Flow failed:', error.message);
  }
}

runFlow();
